# Generated by Django 3.0.5 on 2020-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20200720_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_specialization',
            field=models.CharField(choices=[('Php', 'Php'), ('JS', 'JS'), ('Designing', 'Designing'), ('Application development', 'Application development'), ('Painting', 'Painting'), ('Arts', 'Arts'), ('Development', 'Development'), ('Modeling', 'Modeling'), ('SEO', 'SEO'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('SMM', 'SMM'), ('Culinary Arts', 'Culinary Arts'), ('Peruvian Cuisine', 'Peruvian Cuisine'), ('Team Management', 'Team Management'), ('patience', 'patience'), ('Commitment', 'Commitment'), ('Team Work', 'Team Work'), ('Flexibility', 'Flexibility'), ('Stress Management', 'Stress Management'), ('Analytical skills', 'Analytical skills'), ('trainings', 'trainings'), ('communication skills', 'communication skills'), ('Food Products', 'Food Products'), ('Education', 'Education'), ('cooking', 'cooking')], default='Php', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_specialization',
            field=models.CharField(choices=[('Php', 'Php'), ('JS', 'JS'), ('Designing', 'Designing'), ('Application development', 'Application development'), ('Painting', 'Painting'), ('Arts', 'Arts'), ('Development', 'Development'), ('Modeling', 'Modeling'), ('SEO', 'SEO'), ('Architecture', 'Architecture'), ('Management', 'Management'), ('SMM', 'SMM'), ('Culinary Arts', 'Culinary Arts'), ('Peruvian Cuisine', 'Peruvian Cuisine'), ('Team Management', 'Team Management'), ('patience', 'patience'), ('Commitment', 'Commitment'), ('Team Work', 'Team Work'), ('Flexibility', 'Flexibility'), ('Stress Management', 'Stress Management'), ('Analytical skills', 'Analytical skills'), ('trainings', 'trainings'), ('communication skills', 'communication skills'), ('Food Products', 'Food Products'), ('Education', 'Education'), ('cooking', 'cooking')], default='Php', max_length=200),
        ),
        migrations.AlterField(
            model_name='pay',
            name='plan_id',
            field=models.CharField(choices=[('499 per month', '499 per month'), ('700 for two months', '700 for two months'), ('Yearly subscription @3400', 'Yearly subscription @3400')], default='499 per month', max_length=200),
        ),
    ]
