# Generated by Django 3.1 on 2020-08-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200826_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(default='Under Graduation', max_length=50),
        ),
    ]
