# Generated by Django 3.1 on 2020-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200826_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skilltype',
            field=models.CharField(max_length=50),
        ),
    ]
